
function [variantParamsFlatNames, variantConfigFlatNames] = NameTunableVariants()

%Output  flat names for base workspace
variantParamsFlatNames = {'variantParams_MONTAGE_REFERENTIAL'
    'variantParams_MONTAGE_BIPOLAR'
    'variantParams_PASS_SIGNAL'
    'variantParams_REMOVE_STIM_FREQ'
    'variantParams_REMOVE_ONLY_LINE'
    'variantParams_REAL_WORLD'
    'variantParams_SIMULATION'
    'variantParams_FILTER_FIR_HFORIPPLE'
    'variantParams_FILTER_FIR_RIPPLE'
    'variantParams_FILTER_FIR_HIGHGAMMARIPPLE'
    'variantParams_FILTER_FIR_HIGHGAMMA'
    'variantParams_FILTER_FIR_LOWGAMMA'
    'variantParams_FILTER_FIR_BETA'
    'variantParams_FILTER_FIR_ALPHA'
    'variantParams_FILTER_FIR_THETA'
    'variantParams_FILTER_IIR_HFORIPPLE'
    'variantParams_FILTER_IIR_RIPPLE'
    'variantParams_FILTER_IIR_HIGHGAMMARIPPLE'
    'variantParams_FILTER_IIR_HIGHGAMMA'
    'variantParams_FILTER_IIR_LOWGAMMA'
    'variantParams_FILTER_IIR_BETA'
    'variantParams_FILTER_IIR_ALPHA'
    'variantParams_FILTER_IIR_THETA'
    'variantParams_FILTER_IIR_GAMMA'
    'variantParams_FILTER_IIR_SPINDLES'
    'variantParams_FILTER_FIR_EXTERNAL'
    'variantParams_FILTER_ALLPASS'
    'variantParams_FILTER_MANYFREQS_THETAALPHAGAMMA'
    'variantParams_FEATURE_BANDPOWER'
    'variantParams_FEATURE_VARIANCE'
    'variantParams_FEATURE_COHERENCE'
    'variantParams_FEATURE_CORRELATION'
    'variantParams_FEATURE_SMOOTHBANDPOWER'
    'variantParams_FEATURE_VARIANCEOFPOWER'
    'variantParams_FEATURE_LOGBANDPOWER'
    'variantParams_FEATURE_BASELINE_BANDPOWER'
    'variantParams_FEATURE_BASELINE_VARIANCE'
    'variantParams_FEATURE_BASELINE_SMOOTHBANDPOWER'
    'variantParams_FEATURE_BASELINE_BATCHVARIANCE'
    'variantParams_FEATURE_BASELINE_WEIGHTEDPOWER'
    'variantParams_FEATURE_BASELINE_VARIANCEOFPOWER'
    'variantParams_FEATURE_BASELINE_WEIGHTEDTIMEPOWER'
    'variantParams_FEATURE_BASELINE_COHERENCE'
    'variantParams_FEATURE_BASELINE_CORRELATION'
    'variantParams_DETECTOR_SIMPLEFEATURE'
    'variantParams_DETECTOR_IED'
    'variantParams_DETECTOR_COHERENCEFEATURE'
    'variantParams_DETECTOR_SIMPLEFEATURETRIGGER'
    'variantParams_DETECTOR_COHERENCEFEATURETRIGGER'
    'variantParams_DETECTOR_MULTISITESIMPLEFEATURE'
    'variantParams_DETECTOR_MULTISITECOHERENCETRIGGER'
    'variantParams_STIMULATION_REALTIME'
    'variantParams_STIMULATION_ONNEXTTRIGGER'
    'variantParams_STIMULATION_MULTISITE_REALTIME'
    'variantParams_STIMULATION_MULTISITE_NEXTTRIGGER'
    'variantParams_STIMULATION_TOAMS3800'
    'variantParams_TRIGGER_EEGDATA' 
    'variantParams_TRIGGER_FIXEDPERIOD'
    'variantParams_TRIGGER_FOLLOWINGSTIM'
    'variantParams_TRIGGER_FOLLOWSTIMORFIXED'
    'variantParams_SAMPLING_FS1000'
    'variantParams_SAMPLING_FS2000'
    'variantParams_STATEOUTPUT_MEAN'
    'variantParams_STATEOUTPUT_UPPERBOUND'
    'variantParams_STATEOUTPUT_LOWERBOUND'
    'variantParams_STATEMODEL_NEURALMODEL'};

variantConfigFlatNames = {'variantConfig_IS_BIPOLAR'
'variantConfig_REMOVE_STIM_FREQ'
'variantConfig_IS_SIMULATION'
'variantConfig_FILTER_TYPE'
'variantConfig_FREQ_LOW'
'variantConfig_WHICH_FEATURE'
'variantConfig_WHICH_FEATURE_BASELINE'
'variantConfig_WHICH_DETECTOR'
'variantConfig_STIMULATION_TYPE'
'variantConfig_TRIGGER_TYPE'
'variantConfig_SAMPLINGRATE'
'variantConfig_STATEOUTPUT'
'variantConfig_STATEMODEL'};


%    'variantParams_DETECTOR_STATEESTIMATE'
%    'variantParams_DETECTOR_MULTISITE'
