function Hd = FIRequirriple_70_100(Fs)
%FIREQUIRRIPLE_70_100 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 04-Aug-2016 17:03:55

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
if ~exist('Fs','var')
    Fs = 2000;  % Sampling Frequency
end

Fstop1 = 45;              % First Stopband Frequency
Fpass1 = 70;              % First Passband Frequency
Fpass2 = 100;             % Second Passband Frequency
Fstop2 = 125;             % Second Stopband Frequency
Dstop1 = 0.031622776602;  % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.031622776602;  % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
    0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
